/**
 * Custom worker entrypoint.
 *
 * OpenNext generates `.open-next/worker.js` with only a `fetch` handler. We
 * wrap it here to add `scheduled`, so the CRM engine tick and the social
 * publish tick run on a native Cloudflare cron instead of a GitHub Action.
 *
 * Why the move: a scheduled GitHub Action is throttled — in practice it can
 * deliver roughly hourly and then go silent for hours, so time-critical
 * onboarding email simply never fires. Every run "succeeds"; the emails just
 * don't go out. Cloudflare cron is first-party to the worker and doesn't get
 * deprioritised.
 *
 * Both jobs are driven through synthetic requests to the app's own routes
 * rather than by importing their internals directly. That keeps one code path
 * for both manual and scheduled runs, guarantees the Next.js request context
 * (env, async local storage) is initialised the way the routes already expect,
 * and — because the request never leaves the worker — skips any zone WAF that
 * blocks non-browser user agents.
 */
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, which
// runs AFTER `next build` — so it never resolves during the type-check step of
// the build that creates it. tsconfig's `exclude` cannot prevent this:
// `wrangler types` writes `typeof import("./worker")` into cloudflare-env.d.ts,
// so this file is pulled back in as a transitive dependency. Wrangler bundles
// the real module at deploy time.
// @ts-expect-error -- generated at build time
import openNextHandler from "./.open-next/worker.js";

// @ts-expect-error -- generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

const TICK_PATH = "/api/crm/tick";
const SOCIAL_TICK_PATH = "/api/social/tick";

/**
 * Origin for the synthetic self-requests. The request is handed straight to
 * the OpenNext handler and never leaves the worker, so this only needs to be
 * a well-formed URL — set BACKEND_ORIGIN in wrangler.jsonc `vars` if your
 * routes ever depend on the host header.
 */
function origin(env: CloudflareEnv): string {
  return (env as unknown as Record<string, string>).BACKEND_ORIGIN || "https://backend.localhost";
}

async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * POST a signed machine request to one of our own routes.
 * Signature contract (src/lib/api/auth.ts): METHOD:pathname:timestamp:body.
 */
async function callSigned(
  env: CloudflareEnv,
  ctx: ExecutionContext,
  path: string,
  payload: Record<string, unknown>
): Promise<Response> {
  const secret = (env as unknown as Record<string, string>).API_SECRET_KEY;
  if (!secret) throw new Error("API_SECRET_KEY missing from env");

  const timestamp = Math.floor(Date.now() / 1000).toString();
  const body = JSON.stringify(payload);
  const signature = await hmacHex(secret, `POST:${path}:${timestamp}:${body}`);

  return openNextHandler.fetch(
    new Request(`${origin(env)}${path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": secret,
        "x-timestamp": timestamp,
        "x-signature": signature,
      },
      body,
    }),
    env,
    ctx
  );
}

async function runTick(env: CloudflareEnv, ctx: ExecutionContext): Promise<void> {
  try {
    const response = await callSigned(env, ctx, TICK_PATH, {});
    if (!response.ok) {
      console.error(`crm tick cron: ${response.status} ${(await response.text()).slice(0, 300)}`);
    }
  } catch (e) {
    console.error(`crm tick cron: ${e instanceof Error ? e.message : String(e)}`);
  }
}

async function runSocialTick(env: CloudflareEnv, ctx: ExecutionContext): Promise<void> {
  try {
    const response = await callSigned(env, ctx, SOCIAL_TICK_PATH, {});
    if (!response.ok) {
      console.error(`social tick cron: ${response.status} ${(await response.text()).slice(0, 300)}`);
      return;
    }
    const result = (await response.json()) as {
      postsDue?: number;
      targetsPublished?: number;
      targetsProcessing?: number;
      targetsFailed?: number;
      metricsRefreshed?: number;
      errors?: string[];
    };
    console.log(
      `social tick cron: due=${result.postsDue || 0} published=${result.targetsPublished || 0} ` +
        `processing=${result.targetsProcessing || 0} failed=${result.targetsFailed || 0} ` +
        `metrics=${result.metricsRefreshed || 0}` +
        (result.errors?.length ? ` errors=[${result.errors.join(" | ")}]` : "")
    );
  } catch (e) {
    console.error(`social tick cron: ${e instanceof Error ? e.message : String(e)}`);
  }
}

function socialSchedulerMode(env: CloudflareEnv): "native" | "external" | "invalid" {
  const configured = (env as unknown as Record<string, string>).SOCIAL_SCHEDULER_MODE;
  if (!configured || configured === "native") return "native";
  if (configured === "external") return "external";
  return "invalid";
}

export default {
  fetch: openNextHandler.fetch,
  async scheduled(_controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil(runTick(env, ctx));
    const mode = socialSchedulerMode(env);
    if (mode === "native") {
      ctx.waitUntil(runSocialTick(env, ctx));
    } else if (mode === "invalid") {
      console.error("social tick cron: invalid SOCIAL_SCHEDULER_MODE; expected native or external");
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
